### ISSUE TITLE
Implement pre-commit support

### ISSUE THREAD

**Issue by kieran-ryan** [kieran-ryan/pyprojectsort#13]
While it is trivial to manually run pyprojectsort from the command line against a pyproject.toml file (e.g. simply `pyprojectsort` within the same directory), it is a task developers must remember to do with each committed change to the file and thus is susceptible to follow-on cleanup work where it is missed. To automate this process and ensure every committed change has been formatted with pyprojectsort, a `pre-commit` git hook can be implemented.

The below is an example of how the tool might be specified inside a `.pre-commit-config.yaml` pre-commit configuration file.

```yaml
  - repo: https://github.com/kieran-ryan/pyprojectsort
    rev: v0.1.1
    hooks:
      - id: pyprojectsort
```
