### ISSUE TITLE
Writing back normalised keys causes issues for tools expected dashes

### ISSUE THREAD

**Issue by kieran-ryan** [kieran-ryan/pyprojectsort#27]
pyprojectsort normalises dashes in key and section names to underscores. While this is useful from the point of view of needing to read the configuration for internal use within an application, by writing it back to the file, we are modifying keys expected by various tools, breaking compatibility with those tools.

## Expected Result

Outputted pyproject keeps dash seperators in keys:

```toml
[build-system]
build-backend = "flit.buildapi"
requires = [
    "flit",
]
```

## Actual Result

Outputted pyproject keeps dash seperators in keys:

```toml
[build_system]
build_backend = "flit.buildapi"
requires = [
    "flit",
]
```

## Reproduction Steps

Run pyproject:

```console
pyprojectsort
```

against a pyproject.toml containing the following:

```toml
[build_system]
build-backend = "flit.buildapi"
requires = [
    "flit",
]
```
