### ISSUE TITLE
Alphabetically sort by section key

### ISSUE THREAD

**Issue by kieran-ryan** [kieran-ryan/pyprojectsort#5]
The keys of pyproject.toml sections are highly susceptible to change as a project matures with time. They are thus difficult to keep aligned across developers and can be a source of merge conflicts. By alphabetically sorting these keys, a standardised formatting can be applied that will ensure the output of each developer is exactly the same.

With an example of the following, unsorted section:

```toml
[tool.mypy]
mypy_path = "pyprojectsort"
exclude = "__init__.py|docs|tests|venv"
files = "."
```

The expect output post-formatting would be the alphabetically sorted section below:

```toml
[tool.mypy]
exclude = "__init__.py|docs|tests|venv"
files = "."
mypy_path = "pyprojectsort"
```
